### ISSUE TITLE
New strateggy

### ISSUE THREAD

**Issue by sanitariu** [Errorname/october-eu-bot#7]
Can we add to the strategy for example Risk level with options like a/b/c/d ?

**Comment by Errorname** [comment]
Great idea! I just pushed a new commit for a new strategy: `RISKLEVELS` (See [documentation](https://github.com/Errorname/october-eu-bot#risk-levels))

**Comment by sanitariu** [comment]
Good ! Can we combine risklevel + threshold so for example if we want to lend 
25 euro to all projects with threshold 3% and risk level B
STRATEGY=THRESHOLD(2,25),RISKLEVEL(B) 
or something like that ?

I tested current risklevel but seems something is missing:

october-eu-bot $ npm run cli

(node:8522) UnhandledPromiseRejectionWarning: Error: Unknown strategy "undefined"
    at getStrategy (/home/dri/miner/october-eu-bot/src/strategies/index.js:11:11)
    at main (/home/dri/miner/october-eu-bot/src/index.js:7:20)
    at Object.<anonymous> (/home/dri/miner/october-eu-bot/src/usage/cli.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8522) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.



I have the following in .env file:

RISKLEVELS(B,50)

**Comment by Errorname** [comment]
You need to provide an array of risklevels. So if you want to invest on A & B projects, you write `RISKLEVELS([A,B],50)`. If you only want those with grades "B", then `RISKLEVELS([B],50)`

> Can we combine risklevel + threshold?

Currently not, I may add it in the future

**Comment by sanitariu** [comment]
Thank you. Working now as separate strateggy.
Do i have to create new ticket for combining them or you added to your todo list ?
